// <auto-generated />
using System;
using QuickRegister.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace QuickRegister.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260208112537_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.23");

            modelBuilder.Entity("QuickRegister.Models.AppState", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<int>("Value")
                        .HasColumnType("INTEGER");

                    b.HasKey("Key");

                    b.ToTable("app_state", (string)null);
                });

            modelBuilder.Entity("QuickRegister.Models.Bedrijf", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdresNummer")
                        .HasColumnType("TEXT");

                    b.Property<string>("BedrijfNaam")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Land")
                        .HasColumnType("TEXT");

                    b.Property<string>("Postcode")
                        .HasColumnType("TEXT");

                    b.Property<string>("Stad")
                        .HasColumnType("TEXT");

                    b.Property<string>("StraatNaam")
                        .HasColumnType("TEXT");

                    b.Property<int>("klantId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("bedrijven", (string)null);
                });

            modelBuilder.Entity("QuickRegister.Models.Interventie", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdresNummer")
                        .HasColumnType("TEXT");

                    b.Property<int>("Afgerond")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("BedrijfNaam")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("IdRecentsteCall")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KlantId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Land")
                        .HasColumnType("TEXT");

                    b.Property<string>("Machine")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Postcode")
                        .HasColumnType("TEXT");

                    b.Property<string>("Stad")
                        .HasColumnType("TEXT");

                    b.Property<string>("StraatNaam")
                        .HasColumnType("TEXT");

                    b.Property<int>("TotaleLooptijd")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("interventies", (string)null);
                });

            modelBuilder.Entity("QuickRegister.Models.InterventieCall", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContactpersoonEmail")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactpersoonNaam")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactpersoonTelefoonNummer")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EindCall")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExterneNotities")
                        .HasColumnType("TEXT");

                    b.Property<string>("InterneNotities")
                        .HasColumnType("TEXT");

                    b.Property<int>("InterventieId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MedewerkerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("StartCall")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InterventieId");

                    b.HasIndex("MedewerkerId");

                    b.ToTable("interventie_call", (string)null);
                });

            modelBuilder.Entity("QuickRegister.Models.Medewerker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("medewerkers", (string)null);
                });

            modelBuilder.Entity("QuickRegister.Models.InterventieCall", b =>
                {
                    b.HasOne("QuickRegister.Models.Interventie", "Interventie")
                        .WithMany("Calls")
                        .HasForeignKey("InterventieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuickRegister.Models.Medewerker", "Medewerker")
                        .WithMany()
                        .HasForeignKey("MedewerkerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Interventie");

                    b.Navigation("Medewerker");
                });

            modelBuilder.Entity("QuickRegister.Models.Interventie", b =>
                {
                    b.Navigation("Calls");
                });
#pragma warning restore 612, 618
        }
    }
}
